### ISSUE TITLE
Feature Request: HomeKit Adaptive lighting

### ISSUE THREAD

**Issue by edelmaca** [brutella/hkknx-public#244] opened 2022-12-21 13:53 UTC
I wanted to ask if it is possible to add the adaptive lighting feature of some Lights that can be added to HomeKit with this Homebridge Plugin (https://github.com/ebaauw/homebridge-hue). 
I know, some KNX Dimmer actors can simulate such function with HumanCentricLight (HLC), but these are just a few different set of colors set for specific times scattered over the day, sometimes based on sunrise and sunset times. 
Maybe this is a feature that could be added to your nice Programm and would interest others as well.

**Comment by brutella** [comment] 2022-12-21 14:47
Duplicate of #164

**Closed by brutella** 2022-12-21 14:47 UTC

**Comment by edelmaca** [comment] 2022-12-21 17:49
Oh, sorry. I searched for the same topic in closed section but have not seen one. This one must have slipped my sight.
